# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.08.19
_src_path: gh:scientific-python/cookie
backend: hatch
email: scottyh@uw.edu
full_name: Scott Henderson
license: MIT
org: uw-cryo
project_name: coincident
project_short_description: Search and analysis of STV Precursor Coincident Datasets
url: https://github.com/uw-cryo/coincident
vcs: true
