# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "latest"
  jobs:
    # NOTE: not sure how to modify PATH to just run 'pixi'
    # https://github.com/readthedocs/readthedocs.org/issues/6311...
    install:
      - curl -fsSL https://pixi.sh/install.sh | bash
    build:
      html:
        - /home/docs/.pixi/bin/pixi run docs
        - mkdir -p $READTHEDOCS_OUTPUT/html
        - mv docs/_build/html $READTHEDOCS_OUTPUT/html
